name: Build package thingy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Resolve dependencies
        run: sudo apt install make gcc python3-pip libpython3.*-dev python3-dev && python3 -m pip install Cython
      - name: Build
        run: make all
