name: Build package thingy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Resolve dependencies
        run: sudo apt install make gcc cython python3 python3-dev
      - name: Build
        run: make all
